// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GALV_CharacterFramesMZ","status":true,"description":"(v.1.0) Enables map character sheets to have more frames per character.","parameters":{"fSpeedMod":"f * 0.8","fileSymbol":"%"}},
{"name":"GALV_CFStepSEMZ","status":true,"description":"(v.1.0) Adds step sound effects to Galv's Character Frames plugin","parameters":{"sFrames":"1","events":"true","-- Terrain Step SE --":"","Terrain 1":"Footstep2,35,50","Terrain 2":"Footstep3,35,50","Terrain 3":"Footstep1,35,100","Terrain 4":"Footstep9,35,100","Terrain 5":"","Terrain 6":"","Terrain 7":""}},
{"name":"GALV_MessageStylesMZ","status":true,"description":"(v.1.8) 'Show Text' windows float above characters and change visuals during game.","parameters":{"iIndicator":"2,0,-12","mPadding":"0,0,0,0","invertPos":"true","aGraphic":"WindowArrow","yOffset":"60"}},
{"name":"ThaiFontAutoAdjuster","status":true,"description":"ปรับตัวอักษรภาษาไทยไปตามยถากรรม","parameters":{}},
{"name":"MOG_Weather_EX","status":true,"description":"(v1.3) Adiciona novos efeitos de climas.","parameters":{"Battle Weather":"true","/":""}},
{"name":"MOG_EventSensor","status":true,"description":"(v1.0) Sistema de distância de eventos.","parameters":{"Self Switch Key":"D"}},
{"name":"GALV_MoveRouteExtrasMZ","status":true,"description":"(v.1.1) Additional SCRIPT commands to use within MOVE ROUTES\r\nView the plugin \"Help\" to view available commands.","parameters":{}}
];
